from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd


PROJECT_ROOT = Path(__file__).resolve().parents[3]
SRC_ROOT = PROJECT_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from redteam.utils.paths import project_root
from redteam.utils.scoring import clip_score, percentile_rank


DEFAULT_STOREFRONT_BUILDING_USES = ("제1종근린생활", "제2종근린생활", "판매")


def parse_args() -> argparse.Namespace:
    root = project_root()
    parser = argparse.ArgumentParser(
        description="Build a first-pass district risk score from monthly transaction summaries."
    )
    parser.add_argument(
        "--raw-input",
        default=str(root / "data" / "raw" / "molit_commercial_sales" / "seoul_commercial_sales.csv"),
        help="Optional row-level transaction CSV. When available, storefront filtering is applied before scoring.",
    )
    parser.add_argument(
        "--input",
        default=str(root / "data" / "processed" / "seoul_commercial_sales_monthly_summary.csv"),
        help="Monthly summary CSV generated by collect_molit_commercial_sales.py",
    )
    parser.add_argument(
        "--output",
        default=str(root / "data" / "processed" / "seoul_transaction_risk_scores.csv"),
        help="District risk score output path.",
    )
    parser.add_argument(
        "--history-output",
        default=str(root / "data" / "processed" / "seoul_transaction_risk_history.csv"),
        help="Feature panel output path for debugging and charting.",
    )
    parser.add_argument(
        "--building-uses",
        default=",".join(DEFAULT_STOREFRONT_BUILDING_USES),
        help="Comma-separated building-use labels to treat as storefront-oriented transactions.",
    )
    parser.add_argument(
        "--low-sample-threshold",
        type=int,
        default=10,
        help="Transaction-count threshold below which the latest month is flagged as a low-sample month.",
    )
    return parser.parse_args()


def parse_building_uses(raw_value: str) -> tuple[str, ...]:
    uses = tuple(item.strip() for item in raw_value.split(",") if item.strip())
    if not uses:
        raise ValueError("--building-uses must contain at least one value.")
    return uses


def safe_pct_delta(current: pd.Series, baseline: pd.Series) -> pd.Series:
    baseline = baseline.where(baseline != 0)
    return ((current - baseline) / baseline) * 100


def sample_reliability_label(transaction_count: pd.Series, threshold: int) -> pd.Series:
    low_cutoff = max(threshold, 1)
    medium_cutoff = max(threshold * 2, low_cutoff + 1)

    labels = pd.Series("High", index=transaction_count.index, dtype="object")
    labels.loc[transaction_count < medium_cutoff] = "Medium"
    labels.loc[transaction_count < low_cutoff] = "Low"
    return labels


def build_summary_from_raw(raw_df: pd.DataFrame, building_uses: tuple[str, ...]) -> pd.DataFrame:
    required_cols = {
        "deal_year_month",
        "district_code",
        "district_name_kr",
        "district_name_en",
        "buildingUse",
        "deal_amount_10k_krw",
        "price_per_sqm_10k_krw",
        "building_area_sqm",
        "build_year_num",
    }
    missing_cols = sorted(required_cols - set(raw_df.columns))
    if missing_cols:
        raise ValueError(f"Raw input is missing required columns: {', '.join(missing_cols)}")

    working_df = raw_df.copy()
    working_df["deal_year_month"] = working_df["deal_year_month"].astype(str)
    working_df["district_code"] = working_df["district_code"].astype(str).str.zfill(5)
    working_df["district_name_en"] = working_df["district_name_en"].fillna("")
    working_df["district_name_kr"] = working_df["district_name_kr"].fillna("")
    working_df["buildingUse"] = working_df["buildingUse"].fillna("")

    filtered_df = working_df.loc[working_df["buildingUse"].isin(building_uses)].copy()

    district_df = (
        working_df[["district_code", "district_name_kr", "district_name_en"]]
        .drop_duplicates(subset=["district_code"])
        .sort_values("district_code")
        .reset_index(drop=True)
    )
    month_df = pd.DataFrame({"deal_year_month": sorted(working_df["deal_year_month"].unique().tolist())})
    month_df["join_key"] = 1
    district_df["join_key"] = 1
    scaffold_df = month_df.merge(district_df, on="join_key", how="inner").drop(columns=["join_key"])

    if filtered_df.empty:
        scaffold_df["transaction_count"] = 0
        scaffold_df["median_deal_amount_10k_krw"] = pd.NA
        scaffold_df["mean_deal_amount_10k_krw"] = pd.NA
        scaffold_df["median_price_per_sqm_10k_krw"] = pd.NA
        scaffold_df["mean_price_per_sqm_10k_krw"] = pd.NA
        scaffold_df["median_building_area_sqm"] = pd.NA
        scaffold_df["median_build_year"] = pd.NA
        return scaffold_df

    summary_df = (
        filtered_df.groupby(
            ["deal_year_month", "district_code", "district_name_kr", "district_name_en"],
            dropna=False,
        )
        .agg(
            transaction_count=("deal_amount_10k_krw", "size"),
            median_deal_amount_10k_krw=("deal_amount_10k_krw", "median"),
            mean_deal_amount_10k_krw=("deal_amount_10k_krw", "mean"),
            median_price_per_sqm_10k_krw=("price_per_sqm_10k_krw", "median"),
            mean_price_per_sqm_10k_krw=("price_per_sqm_10k_krw", "mean"),
            median_building_area_sqm=("building_area_sqm", "median"),
            median_build_year=("build_year_num", "median"),
        )
        .reset_index()
    )

    summary_df = scaffold_df.merge(
        summary_df,
        on=["deal_year_month", "district_code", "district_name_kr", "district_name_en"],
        how="left",
    )
    summary_df["transaction_count"] = summary_df["transaction_count"].fillna(0).astype(int)
    return summary_df.sort_values(["deal_year_month", "district_code"]).reset_index(drop=True)


def build_history(summary_df: pd.DataFrame) -> pd.DataFrame:
    df = summary_df.copy()
    df["deal_year_month"] = df["deal_year_month"].astype(str)
    df = df.sort_values(["district_code", "deal_year_month"]).reset_index(drop=True)

    grouped = df.groupby("district_code", dropna=False)
    df["price_per_sqm_3m_avg"] = grouped["median_price_per_sqm_10k_krw"].transform(
        lambda s: s.rolling(3, min_periods=1).mean()
    )
    df["price_per_sqm_6m_avg"] = grouped["median_price_per_sqm_10k_krw"].transform(
        lambda s: s.rolling(6, min_periods=2).mean()
    )
    df["transaction_count_3m_avg"] = grouped["transaction_count"].transform(
        lambda s: s.rolling(3, min_periods=1).mean()
    )
    df["transaction_count_6m_avg"] = grouped["transaction_count"].transform(
        lambda s: s.rolling(6, min_periods=2).mean()
    )
    df["price_volatility_6m"] = grouped["median_price_per_sqm_10k_krw"].transform(
        lambda s: s.rolling(6, min_periods=3).std()
    )

    df["price_growth_3m_pct"] = safe_pct_delta(
        df["median_price_per_sqm_10k_krw"], df["price_per_sqm_3m_avg"]
    )
    df["price_growth_6m_pct"] = safe_pct_delta(
        df["median_price_per_sqm_10k_krw"], df["price_per_sqm_6m_avg"]
    )
    df["transaction_drop_vs_6m_pct"] = safe_pct_delta(
        df["transaction_count"], df["transaction_count_6m_avg"]
    )
    return df


def make_risk_summary(row: pd.Series) -> str:
    drivers: list[str] = []

    if row["price_burden_risk_score"] >= 70:
        growth = row.get("price_growth_6m_pct")
        if pd.notna(growth):
            drivers.append(f"price burden is elevated, with 6m price growth at {growth:.1f}%")
        else:
            drivers.append("price burden is elevated relative to Seoul peers")

    if row["liquidity_risk_score"] >= 70:
        txn = row.get("transaction_count")
        drop = row.get("transaction_drop_vs_6m_pct")
        if pd.notna(txn) and pd.notna(drop):
            drivers.append(
                f"transaction liquidity is weak, with {int(txn)} deals and a {drop:.1f}% change vs 6m average"
            )
        else:
            drivers.append("transaction liquidity is weak relative to Seoul peers")

    if row["volatility_risk_score"] >= 70:
        drivers.append("price volatility has been high in recent months")

    if bool(row.get("low_sample_flag", False)):
        txn = row.get("transaction_count")
        drivers.append(
            f"the latest month only has {int(txn)} storefront trades, so price signals should be treated as thin"
        )

    if not drivers:
        drivers.append("no single transaction signal is flashing red, but the district still warrants monitoring")

    return "; ".join(drivers)


def build_latest_scores(history_df: pd.DataFrame, low_sample_threshold: int) -> pd.DataFrame:
    latest_month = history_df["deal_year_month"].max()
    latest_df = history_df.loc[history_df["deal_year_month"] == latest_month].copy()

    latest_df["price_level_score"] = percentile_rank(
        latest_df["median_price_per_sqm_10k_krw"], ascending=True
    )
    latest_df["price_growth_score"] = percentile_rank(
        latest_df["price_growth_6m_pct"], ascending=True
    )
    latest_df["liquidity_score"] = percentile_rank(
        latest_df["transaction_count"], ascending=False
    )
    latest_df["transaction_drop_score"] = percentile_rank(
        latest_df["transaction_drop_vs_6m_pct"], ascending=False
    )
    latest_df["volatility_score"] = percentile_rank(
        latest_df["price_volatility_6m"], ascending=True
    )

    latest_df["price_burden_risk_score"] = clip_score(
        latest_df["price_level_score"] * 0.65 + latest_df["price_growth_score"] * 0.35
    )
    latest_df["liquidity_risk_score"] = clip_score(
        latest_df["liquidity_score"] * 0.55 + latest_df["transaction_drop_score"] * 0.45
    )
    latest_df["volatility_risk_score"] = clip_score(latest_df["volatility_score"])
    latest_df["low_sample_flag"] = latest_df["transaction_count"] < low_sample_threshold
    latest_df["sample_reliability"] = sample_reliability_label(
        latest_df["transaction_count"], low_sample_threshold
    )
    latest_df["overall_transaction_risk_score"] = clip_score(
        latest_df["price_burden_risk_score"] * 0.5
        + latest_df["liquidity_risk_score"] * 0.3
        + latest_df["volatility_risk_score"] * 0.2
    )
    latest_df["risk_grade"] = pd.cut(
        latest_df["overall_transaction_risk_score"],
        bins=[-1, 35, 55, 75, 100],
        labels=["Low", "Moderate", "High", "Very High"],
    ).astype(str)
    latest_df["primary_risk_driver"] = latest_df[
        ["price_burden_risk_score", "liquidity_risk_score", "volatility_risk_score"]
    ].idxmax(axis=1)
    latest_df["risk_summary"] = latest_df.apply(make_risk_summary, axis=1)

    ordered_columns = [
        "deal_year_month",
        "district_code",
        "district_name_kr",
        "district_name_en",
        "transaction_count",
        "median_deal_amount_10k_krw",
        "median_price_per_sqm_10k_krw",
        "price_growth_3m_pct",
        "price_growth_6m_pct",
        "transaction_drop_vs_6m_pct",
        "price_volatility_6m",
        "price_burden_risk_score",
        "liquidity_risk_score",
        "volatility_risk_score",
        "low_sample_flag",
        "sample_reliability",
        "overall_transaction_risk_score",
        "risk_grade",
        "primary_risk_driver",
        "risk_summary",
    ]
    return latest_df[ordered_columns].sort_values(
        ["overall_transaction_risk_score", "district_code"], ascending=[False, True]
    )


def ensure_parent(path_str: str) -> Path:
    path = Path(path_str).resolve()
    path.parent.mkdir(parents=True, exist_ok=True)
    return path


def main() -> int:
    args = parse_args()
    building_uses = parse_building_uses(args.building_uses)
    input_path = Path(args.input).resolve()
    raw_input_path = Path(args.raw_input).resolve()
    if not input_path.exists() and not raw_input_path.exists():
        print(f"Missing input summary file: {input_path}", file=sys.stderr)
        return 1

    if raw_input_path.exists():
        raw_df = pd.read_csv(raw_input_path)
        summary_df = build_summary_from_raw(raw_df, building_uses)
    else:
        summary_df = pd.read_csv(input_path)
        required_cols = {
            "deal_year_month",
            "district_code",
            "district_name_kr",
            "district_name_en",
            "transaction_count",
            "median_deal_amount_10k_krw",
            "median_price_per_sqm_10k_krw",
        }
        missing_cols = sorted(required_cols - set(summary_df.columns))
        if missing_cols:
            print(f"Input file is missing required columns: {', '.join(missing_cols)}", file=sys.stderr)
            return 1

    history_df = build_history(summary_df)
    score_df = build_latest_scores(history_df, low_sample_threshold=args.low_sample_threshold)

    output_path = ensure_parent(args.output)
    history_output_path = ensure_parent(args.history_output)
    score_df.to_csv(output_path, index=False, encoding="utf-8-sig")
    history_df.to_csv(history_output_path, index=False, encoding="utf-8-sig")

    print(f"Saved district scores: {len(score_df):,} -> {output_path}")
    print(f"Saved feature history: {len(history_df):,} -> {history_output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
